server:
    port : 8002

#api
services:
    hotsName : http://192.90.20.232:8001
    productAPI : /products
    categoryAPI : /categories
    userAPI : /api/v1/users
    roleAPI : /role
    addressAPI : /address
    promotionAPI : /promotions
    token : /api/authenticate
    order : /orderDetails

