server:
    port : 8002

#api
services:
    hotsName : http://localhost:8001
    productAPI : /products
    categoryAPI : /categories
    userAPI : /user
    roleAPI : /role
    addressAPI : /address
    promotionAPI : /promotions
    token : /authenticate
    order : /orderDetails

