server:
    port : 8003

#api
services:
    hotsName : http://localhost:8002
    productAPI : /api/products
    categoryAPI : /api/categories
    userAPI : /api/user
    roleAPI : /role
    token : /api/authenticate


